### ISSUE TITLE
[FEATURE] “Andromeda” Scaffold Type

### ISSUE THREAD

**Issue by liquidsquid1** [CCBlueX/LiquidBounce#2888] opened 2024-04-21 20:01 UTC
### LiquidBounce Branch

Nextgen

### Describe your feature request.

There should be a scaffold type which places blocks above and below your head, and spams space to build momentum.

### Additional context

This would be especially good on servers with bad anticheats. The scaffold should ideally only function if there is a rotation to place the block above your head, otherwise it would follow normal scaffold logic.

**Comment by EclipsesDev** [comment] 2024-04-21 23:41
example of bad anticheats?

**Comment by EclipsesDev** [comment] 2024-04-21 23:42
since most bad anticheats will likely to false flag it anyway

**Comment by liquidsquid1** [comment] 2024-04-22 05:33
> example of bad anticheats?

It would probably even work on blocksmc as half of the checks are disabled 💀

**Comment by EclipsesDev** [comment] 2024-04-22 07:00
Well u forgot ncp angle check.. its quite sensitive and most likely to false flag it.. for fast rotation & angle

**Comment by Razzy52** [comment] 2024-04-22 08:34
duplicate of #2069

**Closed as completed** 2024-04-22 08:36 UTC
Labels: 🔥 enhancement, 👷 development build, 🌑 nextgen
