### ISSUE TITLE
[BUG] Critical issues with legacy LB

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce#817] opened 2022-07-28 08:41 UTC
### LiquidBounce Build/Version

b73 9139e0b and newer

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

Since [Forge Gradle plugin update](https://github.com/CCBlueX/LiquidBounce/commit/9139e0b848946fa9814d1507838616447afb37a1), ScriptAPI is acting weird and it's totally unusable, **pretty much all scripts don't work**.
mc returns Minecraft instance, however mc.thePlayer returns undefined
If you downgrade to build before that everything works.
SRG stuff, Nashorn incompatibility or smth?

**AltManager doesn't load saved alts** after starting the game. It only stores them as long as you add them and they get deleted after restarting game. Saving to accounts.json works but loading from that file doesn't work at start it seems.

**Cannot log in with microsoft accounts:**
`Error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

When changing **text values**, LB joins the arguments so that **you cannot input spaces now**.
Makes you unable to do .inventorymanager slot1 Diamond Sword, Golden Apple, .... because it sets slot1 to DiamondSword,GoldenApple,...
This should be changed back to how it was until cross-version.

When you enable **InvCleaner, ChestStealer, AutoArmor** with ItemDelay and stuff, the game starts **freezing** without any errors in log, didn't have enough patience to test this shit thoroughly. But can reproduce it easily.

### Steps to reproduce

.

### Client Log

```shell
.
```

**Comment by ghost** [comment] 2022-07-28 17:21
> When you enable **InvCleaner, ChestStealer, AutoArmor** with ItemDelay and stuff, the game starts **freezing** without any errors in log, didn't have enough patience to test this shit thoroughly. But can reproduce it easily.

Does this occur when you open a chest with ChestStealer enabled?

**Comment by CzechHek** [comment] 2022-07-28 19:13
> > When you enable **InvCleaner, ChestStealer, AutoArmor** with ItemDelay and stuff, the game starts **freezing** without any errors in log, didn't have enough patience to test this shit thoroughly. But can reproduce it easily.
> 
> Does this occur when you open a chest with ChestStealer enabled?

Even by standing in lobby.

**Comment by ghost** [comment] 2022-07-28 20:01
Do you mind creating a video? I can't reproduce it. I've only noticed this issue when opening a chest.

**Comment by CzechHek** [comment] 2022-07-28 20:08
> Do you mind creating a video? I can't reproduce it. I've only noticed this issue when opening a chest.

Selecting a server in the lobby could have triggered it since that's GuiChest, but that's the smallest issue from all of mentioned.

**Comment by 1zun4secondary** [comment] 2023-02-19 12:37
fixed by https://github.com/CCBlueX/LiquidBounce/commit/8e464765e5d906a3e8cd0ad780add68f73101d8

**Closed as completed by 1zun4secondary** 2023-02-19 12:37 UTC
