### ISSUE TITLE
[FEATURE] When will liquidbounce support minecraft 1.17

### ISSUE THREAD

**Issue by acepirine** [CCBlueX/LiquidBounce#558] opened 2021-07-01 06:57 UTC
### Describe your feature request.

I am not familiar with any java stuff but how hard is it to update to 1.17? you should definitely try doing that

**Comment by NurMarvin** [comment] 2021-07-01 07:22
Already planned and being worked in https://github.com/CCBlueX/LiquidBounce/tree/nextgen_1.17
Duplicate of #167

**Closed as completed by NurMarvin** 2021-07-01 07:22 UTC
