### ISSUE TITLE
[BUG] .binds list is broken

### ISSUE THREAD

**Issue by Rynav** [CCBlueX/LiquidBounce#639] opened 2021-08-23 21:57 UTC
### LiquidBounce Build/Version

Nextgen

### Operating System

Windows 10

### Minecraft Version

1.17.1

### Describe the bug

.binds list display is broken

### Steps to reproduce

 - add some binds
 - type .binds list
 - done

### Client Log

```shell
Nothing relevant
```

### Screenshots

![obraz](https://user-images.githubusercontent.com/61330994/130524813-252b5ef9-4741-4f6d-8d0e-b307e46d633a.png)

**Comment by ghost** [comment] 2022-01-08 18:44
@Rynav, the issue is now fixed. You can now close your issue.

**Closed as completed** 2022-01-09 16:44 UTC
