### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bluecxt** [CCBlueX/LiquidBounce#1702] opened 2023-12-18 17:23 UTC
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

latest

### Operating System

Linux

### Minecraft Version

1.20.4

### Describe the bug

crash after the minecraft windows

### Steps to reproduce

?

### Client Log

```shell
https://paste.ccbluex.net/4b6acda5c



[18:19:51] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.1
[18:19:51] [ForkJoinPool-1-worker-3/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR1-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[18:19:51] [main/INFO]: Loading 95 mods:
	- fabric-api 0.91.2 1.20.4
	   |-- fabric-api-base 0.4.35 78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.45 78d798af4f
	   |-- fabric-biome-api-v1 13.0.15 78d798af4f
	   |-- fabric-block-api-v1 1.0.14 78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3 78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45 78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6 78d798af4f
	   |-- fabric-command-api-v1 1.2.40 f71b366f4f
	   |-- fabric-command-api-v2 2.2.19 78d798af4f
	   |-- fabric-commands-v0 0.2.57 df3654b34f
	   |-- fabric-containers-v0 0.1.81 df3654b34f
	   |-- fabric-content-registries-v0 5.0.9 78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9 78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22 78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17 78d798af4f
	   |-- fabric-dimensions-v1 2.1.60 78d798af4f
	   |-- fabric-entity-events-v1 1.5.27 78d798af4f
	   |-- fabric-events-interaction-v0 0.6.14 78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71 df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45 78d798af4f
	   |-- fabric-item-api-v1 2.1.34 78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20 78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40 78d798af4f
	   |-- fabric-keybindings-v0 0.2.38 df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.29 78d798af4f
	   |-- fabric-loot-api-v2 2.1.4 78d798af4f
	   |-- fabric-message-api-v1 6.0.4 78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59 78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7 78d798af4f
	   |-- fabric-models-v0 0.4.6 9386d8a74f
	   |-- fabric-networking-api-v1 3.1.2 78d798af4f
	   |-- fabric-object-builder-api-v1 13.0.7 78d798af4f
	   |-- fabric-particles-v1 1.1.6 78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15 78d798af4f
	   |-- fabric-registry-sync-v0 4.0.13 78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3 78d798af4f
	   |-- fabric-renderer-indigo 1.5.3 78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50 df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.41 73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.32 78d798af4f
	   |-- fabric-rendering-v0 1.1.53 df3654b34f
	   |-- fabric-rendering-v1 3.0.12 78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13 78d798af4f
	   |-- fabric-resource-loader-v0 0.11.15 78d798af4f
	   |-- fabric-screen-api-v1 2.0.16 78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50 78d798af4f
	   |-- fabric-sound-api-v1 1.0.16 78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6 78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13 78d798af4f
	- fabric-language-kotlin 1.9.4 kotlin.1.8.21
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- java 17
	- liquidbounce 1.0.0
	- minecraft 1.20.4
	- modmenu 9.0.0-pre.1
	- nochatreports 1.20.4-v2.5.0
	- sodium 0.5.5
	- viafabricplus 3.0.2
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- com_vdurmont_semver4j 3.1.0
	   |-- com_viaversion_viabackwards-common 4.9.2-SNAPSHOT
	   |-- com_viaversion_viaversion-common 4.9.3-SNAPSHOT
	   |-- de_florianmichael_classic4j 2.0.1
	   |-- io_jsonwebtoken_jjwt-api 0.12.3
	   |-- io_jsonwebtoken_jjwt-gson 0.12.3
	   |-- io_jsonwebtoken_jjwt-impl 0.12.3
	   |-- net_jodah_expiringmap 0.5.10
	   |-- net_lenni0451_mcping 1.3.0
	   |-- net_lenni0451_mcstructs-bedrock_forms 1.2.0
	   |-- net_lenni0451_mcstructs-bedrock_text 1.2.0
	   |-- net_lenni0451_mcstructs_core 2.4.1
	   |-- net_lenni0451_mcstructs_nbt 2.4.1
	   |-- net_lenni0451_mcstructs_snbt 2.4.1
	   |-- net_lenni0451_mcstructs_text 2.4.1
	   |-- net_lenni0451_reflect 1.3.1
	   |-- net_raphimc_minecraftauth 3.0.1-SNAPSHOT
	   |-- net_raphimc_viaaprilfools 2.0.11-SNAPSHOT
	   |-- net_raphimc_viabedrock 0.0.4-SNAPSHOT
	   |-- net_raphimc_vialegacy 2.2.22-SNAPSHOT
	   |-- net_raphimc_vialoader 2.2.13-SNAPSHOT
	   |-- org_cloudburstmc_netty_netty-transport-raknet 1.0.0.CR1-SNAPSHOT
	   \-- org_yaml_snakeyaml 2.2
[18:19:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/moi/.local/share/liquidlauncher/libraries/net/fabricmc/sponge-mixin/0.12.5 mixin.0.8.5/sponge-mixin-0.12.5 mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:19:51] [main/INFO]: Compatibility level set to JAVA_17
[18:19:51] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[18:19:52] [main/INFO]: Searching for graphics cards...
[18:19:52] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=GA104M [GeForce RTX 3070 Mobile / Max-Q], version=535.43.19]
[18:19:52] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=TigerLake-H GT1 [UHD Graphics], version=unknown]
[18:19:52] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS, NO_ERROR_CONTEXT_UNSUPPORTED]
[18:19:52] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[18:19:52] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[18:19:53] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[18:19:53] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[18:19:53] [ForkJoinPool.commonPool-worker-1/INFO]: Loading translations...
[18:19:53] [ForkJoinPool.commonPool-worker-1/INFO]: Registering protocols...
[18:19:54] [ForkJoinPool.commonPool-worker-1/INFO]: Started resource pack HTTP server on http://127.0.0.1:38453/
[18:19:54] [ForkJoinPool.commonPool-worker-1/INFO]: ViaVersion detected lowest supported version by the proxy: 1.7.2-1.7.5 (4)
[18:19:54] [ForkJoinPool.commonPool-worker-1/INFO]: Highest supported version by the proxy: 1.20.3-1.20.4 (765)
[18:19:54] [ForkJoinPool.commonPool-worker-1/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:19:55] [main/INFO]: liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntityAccessor from mod liquidbounce->@Accessor[FIELD_GETTER]::getTrackedMainArm()Lnet/minecraft/class_2940; should be static as its target is
[18:19:58] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 168 milliseconds
[18:19:59] [Via Async Scheduler 0/INFO]: Finished mapping loading, shutting down loader executor!
[18:20:00] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:20:00] [Render thread/INFO]: Setting user: bluecxt
[18:20:00] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[18:20:00] [Render thread/WARN]: ClothConfig API not found, cannot provide config screen factory.
[18:20:00] [Worker-Main-1/INFO]: Checking mod updates...
[18:20:00] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[18:20:00] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[18:20:00] [Render thread/INFO]: OpenGL Vendor: Intel
[18:20:00] [Render thread/INFO]: OpenGL Renderer: Mesa Intel(R) UHD Graphics (TGL GT1)
[18:20:00] [Render thread/INFO]: OpenGL Version: 4.6 (Core Profile) Mesa 23.2.1-arch1.2
[18:20:01] [Worker-Main-1/INFO]: Update available for 'fabric-language-kotlin@1.9.4 kotlin.1.8.21', (-> 1.10.16 kotlin.1.9.21)
[18:20:01] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.91.2 1.20.4', (-> 0.91.3 1.20.4)
[18:20:01] [Render thread/INFO]: Launching LiquidBounce v1.0.0 by CCBlueX
[18:20:01] [Render thread/INFO]: Successfully extracted default theme
[18:20:01] [Render thread/INFO]: Loading heads...
[18:20:02] [Render thread/INFO]: Successfully loaded 956 heads from the database
[18:20:02] [Render thread/INFO]: Loading ultralight...
[18:20:02] [Render thread/INFO]: Checking resources...
[18:20:02] [Render thread/INFO]: Loading ultralight natives
[18:20:02] [Render thread/INFO]: Native path: /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin
[18:20:02] [Render thread/ERROR]: Failed to load library gobject-2.0-0
java.lang.UnsatisfiedLinkError: /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgobject-2.0-0.so: /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgobject-2.0-0.so: undefined symbol: g_string_free_and_steal
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:161) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$blk000$liquidbounce$startClient(class_310.java:8845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
[18:20:03] [Render thread/ERROR]: Failed to load library gio-2.0-0
java.lang.UnsatisfiedLinkError: /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgio-2.0-0.so: /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgio-2.0-0.so: undefined symbol: g_hash_table_get_values_as_ptr_array
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:161) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$blk000$liquidbounce$startClient(class_310.java:8845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
[18:20:03] [Render thread/ERROR]: Failed to load library gstreamer-full-1.0
java.lang.UnsatisfiedLinkError: /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libgstreamer-full-1.0.so: libpng12.so.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:161) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$blk000$liquidbounce$startClient(class_310.java:8845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
OpenJDK 64-Bit Server VM warning: You have loaded library /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[18:20:03] [Render thread/ERROR]: Fatal error
com.labymedia.ultralight.UltralightLoadException: Failed to load native dependency WebCore (tried to load from /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so)
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:146) ~[LiquidBounce.jar:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:115) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.initNatives(UltralightEngine.kt:168) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.base.ultralight.UltralightEngine.init(UltralightEngine.kt:69) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:132) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.LiquidBounce$startHandler$1.invoke(LiquidBounce.kt:95) ~[LiquidBounce.jar:?]
	at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:155) ~[LiquidBounce.jar:?]
	at net.minecraft.class_310.handler$blk000$liquidbounce$startClient(class_310.java:8845) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[fabric-loader-0.15.1-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: /home/moi/.local/share/liquidlauncher/gameDir/nextgen/LiquidBounce/ultralight/bin/libWebCore.so: libpng12.so.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at com.labymedia.ultralight.UltralightJava.load(UltralightJava.java:144) ~[LiquidBounce.jar:?]
	... 12 more
zenity: symbol lookup error: /usr/lib/libjson-glib-1.0.so.0: undefined symbol: g_string_free_and_steal
An error with the client occourd:
Process exited with non-zero exit code: 1.
```

**Comment by michael-pfister** [comment] 2023-12-19 10:23
duplicate of #1701

**Closed as not planned** 2023-12-19 12:43 UTC
Labels: 🐛 bug, 👷 development build, 🌑 nextgen
