### ISSUE TITLE
[BUG] cant login with a session id

### ISSUE THREAD

**Issue by afasdfsfdsagddafh** [CCBlueX/LiquidBounce#2243] opened 2024-03-04 16:34 UTC
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b89

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

using a brand new session id from lunar, just says logging in for literally 30 minutes (the most i waited before quitting)

### Steps to reproduce

paste session id
press login 
infinite waiting

### Client Log

```shell
non
```

**Comment by EclipsesDev** [comment] 2024-03-04 23:22
@182exe maybe u know smth about this?

**Comment by 182exe** [comment] 2024-03-05 07:43
i do, and yeah it still doesn't work.
session tokens are basically what you can generate from an authenticated microsoft app (e.g. lunar client's alt manager) that you then use to login to minecraft itself.

here's how forge implements it (first few lines):
https://github.com/MinecraftForkage/MinecraftForge/blob/master/patches/minecraft/net/minecraft/client/Minecraft.java.patch

and heres an example forge mod using this auth system which i personally use w/ the client if i need to use session tokens for whatever reason:
https://github.com/Schubilegend/SchubiAuthV2/

heres a kotlin impl:
https://github.com/TheNullicorn/ms-to-mca

and finally heres the wiki.vg page for ms auth: https://wiki.vg/Microsoft_Authentication_Scheme
on the vg page, the auth bearer is what the session token is

**Comment by EclipsesDev** [comment] 2024-03-05 07:57
> i do, and yeah it still doesn't work. session tokens are basically what you can generate from an authenticated microsoft app (e.g. lunar client's alt manager) that you then use to login to minecraft itself.
> 
> here's how forge implements it (first few lines): https://github.com/MinecraftForkage/MinecraftForge/blob/master/patches/minecraft/net/minecraft/client/Minecraft.java.patch
> 
> and heres an example forge mod using this auth system which i personally use w/ the client if i need to use session tokens for whatever reason: https://github.com/Schubilegend/SchubiAuthV2/
> 
> heres a kotlin impl: https://github.com/TheNullicorn/ms-to-mca
> 
> and finally heres the wiki.vg page for ms auth: https://wiki.vg/Microsoft_Authentication_Scheme on the vg page, the auth bearer is what the session token is

So will u implement the fix?

**Comment by catnoee** [comment] 2024-03-05 13:32
> > i do, and yeah it still doesn't work. session tokens are basically what you can generate from an authenticated microsoft app (e.g. lunar client's alt manager) that you then use to login to minecraft itself.
> > here's how forge implements it (first few lines): https://github.com/MinecraftForkage/MinecraftForge/blob/master/patches/minecraft/net/minecraft/client/Minecraft.java.patch
> > and heres an example forge mod using this auth system which i personally use w/ the client if i need to use session tokens for whatever reason: https://github.com/Schubilegend/SchubiAuthV2/
> > heres a kotlin impl: https://github.com/TheNullicorn/ms-to-mca
> > and finally heres the wiki.vg page for ms auth: https://wiki.vg/Microsoft_Authentication_Scheme on the vg page, the auth bearer is what the session token is
> 
> So will u implement the fix?

he is NOT a dev brah

**Comment by EclipsesDev** [comment] 2024-03-05 13:43
> > > i do, and yeah it still doesn't work. session tokens are basically what you can generate from an authenticated microsoft app (e.g. lunar client's alt manager) that you then use to login to minecraft itself.
> > > here's how forge implements it (first few lines): https://github.com/MinecraftForkage/MinecraftForge/blob/master/patches/minecraft/net/minecraft/client/Minecraft.java.patch
> > > and heres an example forge mod using this auth system which i personally use w/ the client if i need to use session tokens for whatever reason: https://github.com/Schubilegend/SchubiAuthV2/
> > > heres a kotlin impl: https://github.com/TheNullicorn/ms-to-mca
> > > and finally heres the wiki.vg page for ms auth: https://wiki.vg/Microsoft_Authentication_Scheme on the vg page, the auth bearer is what the session token is
> > 
> > 
> > So will u implement the fix?
> 
> he is NOT a dev brah

He is part of LiquidBounce contributor buds..

**Comment by afasdfsfdsagddafh** [comment] 2024-03-05 14:05
> > > > i do, and yeah it still doesn't work. session tokens are basically what you can generate from an authenticated microsoft app (e.g. lunar client's alt manager) that you then use to login to minecraft itself.
> > > > here's how forge implements it (first few lines): https://github.com/MinecraftForkage/MinecraftForge/blob/master/patches/minecraft/net/minecraft/client/Minecraft.java.patch
> > > > and heres an example forge mod using this auth system which i personally use w/ the client if i need to use session tokens for whatever reason: https://github.com/Schubilegend/SchubiAuthV2/
> > > > heres a kotlin impl: https://github.com/TheNullicorn/ms-to-mca
> > > > and finally heres the wiki.vg page for ms auth: https://wiki.vg/Microsoft_Authentication_Scheme on the vg page, the auth bearer is what the session token is
> > > 
> > > 
> > > So will u implement the fix?
> > 
> > 
> > he is NOT a dev brah
> 
> He is part of LiquidBounce contributor buds..

oh LOL mb

**Comment by 182exe** [comment] 2024-03-07 07:04
probably not, im a bit terrible
i would have to learn more kt

if anyone starts working on it i'd love to help

**Comment by EclipsesDev** [comment] 2024-03-07 07:08
> probably not, im a bit terrible i would have to learn more kt
> 
> if anyone starts working on it i'd love to help

I'd help to implement it, tho the problem is that I don't know much about minecraft auth..

**Comment by EclipsesDev** [comment] 2024-03-26 06:13
welp ig, I'll have to learn how mc auth work..

**Comment by 182exe** [comment] 2024-03-28 04:08
the version in nextgen branch works, you can base it off that

**Comment by EclipsesDev** [comment] 2024-03-31 14:33
> the version in nextgen branch works, you can base it off that

ehh idk dude, whatever here take a look at #2685 and heres link for minecraft api related https://wiki.vg/Mojang_API, maybe u know how to fix it, cuz i've tried but idk

**Comment by EclipsesDev** [comment] 2024-04-12 15:43
@catnoee seems like I can't fix this now.. I'd suggest u use mod recommended by @182exe

**Comment by 182exe** [comment] 2024-04-12 16:00
schubiauth is compatible and it works fine yeah

no reason not to use it; maybe remove the button in the client tho

**Comment by afasdfsfdsagddafh** [comment] 2024-07-23 09:29
> schubiauth is compatible and it works fine yeah
> 
> no reason not to use it; maybe remove the button in the client tho

the mod you linked is empty

**Comment by 182exe** [comment] 2024-07-24 05:47
because it's been wiped.

**Comment by EclipsesDev** [comment] 2024-11-11 11:35
well2 its been 8 months xd, but yep session login should be fixed now, sorry for the delay 🙏

**Closed as completed by EclipsesDev** 2024-11-11 11:35 UTC
Labels: 🐛 bug, 🌕 legacy
