### ISSUE TITLE
[BUG] sprint and noslotset are always active regardless of being enabled

### ISSUE THREAD

**Issue by 182exe** [CCBlueX/LiquidBounce#2580] opened 2024-03-24 05:17 UTC
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest build

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

**Sprint:**
If the alldirections sprint is enabled and onholdkey is also enabled, then if the sprint module is enabled or disabled you can still sprint in all directions.

**Noslotset:**
On Minemen specifically, sometimes when winning or losing a game and getting sent back to the lobby your client sided slot will differ from the server sided slot and right or left clicking without first using the scroll wheel to reset your slot again will get you banned. I'm not sure if this is just a Minemen thing.

### Steps to reproduce

**Sprint:**
1. Enable sprint
2. Enable alldirections and onkeyhold
3. Disable sprint
4. Try holding your sprint key and running backwards.

**Noslotset:**
1. Not entirely sure, try just playing on minemen, losing a game and before you get sent back to the lobby set your slot to like 6 or something and wait for yourself to get sent back to spawn.

### Client Log

```shell
ask if needed
```

**Comment by EclipsesDev** [comment] 2024-03-24 05:31
can u provide the setting for the sprint module? cuz i cannot reproduce the same issue

**Comment by EclipsesDev** [comment] 2024-03-24 05:34
also provide log, that would be useful

**Comment by EclipsesDev** [comment] 2024-03-31 09:16
soo..?

**Comment by 182exe** [comment] 2024-03-31 20:20
https://github.com/CCBlueX/LiquidBounce/assets/81325987/e0041e37-f9bb-45db-a2ce-6b1433a9c729

also, the only log that wasnt just a chat message or the config saving if i changed it was this:
```
13:17:21.301
net.minecraft.client.renderer.WorldRenderer
Chunk Batcher 3
Needed to grow BufferBuilder buffer: Old size 524288 bytes, new size 2621440 bytes.
```

**Comment by EclipsesDev** [comment] 2024-04-01 03:24
did u use autoplay?

**Comment by 182exe** [comment] 2024-04-01 06:33
tried checking if it was that earlier; i'm not sure if thats the reason. it happens with it enabled and its disabled.

**Comment by EclipsesDev** [comment] 2024-04-01 11:14
@182exe  try to use #2695 not sure if thats gonna fix ur issue, or causes more issue lol

**Comment by EclipsesDev** [comment] 2024-04-01 14:46
but a yeah, try to build that using inteliJ or whatever idea u have.. 👍

**Comment by 182exe** [comment] 2024-04-01 17:47
i think this works...? i broke intellij on accident yesterday so i'll try again building today.
maybe another fix would be just to change client slot to server slot on world change.

**Comment by EclipsesDev** [comment] 2024-04-04 13:28
> i think this works...? i broke intellij on accident yesterday so i'll try again building today. maybe another fix would be just to change client slot to server slot on world change.

yeah i was thinking about that.. idk know why i didn't do that instead..

**Comment by EclipsesDev** [comment] 2024-04-04 14:04
actually nvm, that'll cause some server to detect badpackets (for some reason)

**Comment by EclipsesDev** [comment] 2024-04-04 14:05
ok i think #2695 should work.. i think.. (my premium account was banned so i couldn't test it out)

**Comment by EclipsesDev** [comment] 2024-04-06 12:16
@182exe so hows it?

**Comment by 182exe** [comment] 2024-04-06 17:03
i couldnt build

**Comment by EclipsesDev** [comment] 2024-04-08 10:37
> i couldnt build

hmm wait maybe cuz the version is upped, but idk.. i'll update it ig

**Comment by EclipsesDev** [comment] 2024-04-12 09:52
Can u build? @182exe, if not maybe i could merge it (for testing)

**Comment by 182exe** [comment] 2024-04-12 15:59
yeah, merge it i guess.

i get a lot of errors with both intellij and eclipse.

**Comment by EclipsesDev** [comment] 2024-04-12 16:08
> yeah, merge it i guess.
> 
> i get a lot of errors with both intellij and eclipse.

I've merge it, go ahead and test it.. if there's smth wrong then probably I'll be fixing it tomorrow 👌

**Comment by 182exe** [comment] 2024-04-12 16:22
alright
i'll do like .panic before testing n stuff

i get home in a lot of hours, so probably wait for a response

**Comment by EclipsesDev** [comment] 2024-04-13 02:33
ok

**Comment by EclipsesDev** [comment] 2024-04-13 10:23
btw @182exe u got discord or smth? i have special req for u

**Comment by 182exe** [comment] 2024-04-14 04:46
yeah, @182exe on dc
also yeah this doesnt work and it breaks cheststealer

**Comment by EclipsesDev** [comment] 2024-04-14 05:03
Yeah I'll fix it soon

**Comment by EclipsesDev** [comment] 2024-04-15 08:50
Go ahead and try #2814

**Comment by EclipsesDev** [comment] 2024-04-15 08:51
should be fixed (i think)

**Closed as completed** 2024-04-20 08:30 UTC
Labels: 🐛 bug, 🌕 legacy
