### ISSUE TITLE
[BUG] Hud text glitch

### ISSUE THREAD

**Issue by FatMolePanda** [CCBlueX/LiquidBounce#3979] opened 2024-09-22 19:50 UTC
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b98 latest

### Operating System

Windows 11

### Minecraft Version

1.8.9

### Describe the bug

the text glitches out when you have the chat open
the hud config https://www.mediafire.com/file/1c3llbqgibbci5s/Nezha_old.json/file

### Steps to reproduce

https://www.mediafire.com/file/1c3llbqgibbci5s/Nezha_old.json/file

### Client Log

```shell
idk
```

### Screenshots

https://imgur.com/vDhffPi

**Comment by EclipsesDev** [comment] 2024-09-23 00:12
post log

**Comment by FatMolePanda** [comment] 2024-09-26 06:13
https://mclo.gs/DvGkHaT

**Comment by EclipsesDev** [comment] 2024-09-26 11:16
does it only happen on singleplayer?

**Comment by FatMolePanda** [comment] 2024-09-27 15:20
it happenes in both mutliplayer and singleplayer

**Comment by ghost** [comment] 2024-12-19 20:49
Try with the latest development build, see if it still exists. If it does, then send us the HUD configuration. @FatMolePanda

**Comment by EclipsesDev** [comment] 2024-12-25 06:18
should be fixed in latest nightly, could not reproduce issue again

**Closed as completed by EclipsesDev** 2024-12-25 06:18 UTC
Labels: 🐛 bug, 🌕 legacy, ✔️ confirmed issue
