### ISSUE TITLE
[BUG] java.io.IOException: Server returned HTTP response code: 401 for URL: https://xsts.auth.xboxlive.com/xsts/authorize

### ISSUE THREAD

**Issue by KaPi404** [CCBlueX/LiquidBounce#803] opened 2022-07-03 07:11 UTC
### LiquidBounce Build/Version

b72

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

I was trying to add an alt that is my Microsoft account (_i do have mc bought, just adding this so people dont ask_) and i got the error java.io.IOException: Server returned HTTP response code: 401 for URL: https://xsts.auth.xboxlive.com/xsts/authorize

EVERY. SINGLE. TRY.
The same happened on another PC.
Not sure if its just me though.
### Steps to reproduce

Go to AltManager
Click on "Add"
Click on "Login with Microsoft"
There it is.

### Client Log

```shell
I couldn't find any relevant client logs.
```

### Screenshots

![image](https://user-images.githubusercontent.com/108606249/177029195-6f478d93-d16e-41fe-b069-ffabb9e2baea.png)

**Comment by 1zun4secondary** [comment] 2023-02-19 15:41
Unable to reproduce. Might be addressed by https://github.com/CCBlueX/LiquidBounce/commit/2cc061709d6d49b3be487dc33c601f4fa159b92b

If not, reopen or notify me.

**Closed as completed by 1zun4secondary** 2023-02-19 15:41 UTC
Labels: 🐛 bug, 🌕 legacy
