### ISSUE TITLE
[BUG] Nametag cannot render UTF-8 characters

### ISSUE THREAD

**Issue by MukjepScarlet** [CCBlueX/LiquidBounce#3302] opened 2024-06-23 11:47 UTC
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.6.1

### Operating System

Windows 10

### Minecraft Version

1.20.6

### Describe the bug

Just like title. Users should be able to change the font of this module.

### Steps to reproduce

Literally...

### Client Log

```shell
Literally...
```

**Comment by larryngton** [comment] 2024-06-25 19:09
duplicate of #2206

**Closed as not planned** 2024-06-25 19:12 UTC
Labels: 🐛 bug, 👷 development build, 🌑 nextgen
