### ISSUE TITLE
[BUG] toggling a module off shows a green checkmark

### ISSUE THREAD

**Issue by Cypphi** [CCBlueX/LiquidBounce#473] opened 2021-05-11 06:44 UTC
**Describe the bug**
When you toggle off a module it shows a popup with a green checkmark instead of a red cross or similar to that.

**To Reproduce**
1. Toggle a module on and then off

**Comment by NurMarvin** [comment] 2021-05-11 06:47
I'm not sure if this is intentional behavior or not. I've definitely wondered the same myself but maybe @SenkJu can give more insight into this since he worked on the HUD.

**Comment by Cypphi** [comment] 2021-05-11 06:50
Yeah I also wasn't sure. And if it's intended I'm suggesting to change it to a red cross because otherwise it's very hard to see what you did without reading.

**Comment by SenkJu** [comment] 2021-05-11 06:51
Currently, it is intended. We might change it.

**Comment by 1zun4secondary** [comment] 2021-05-11 09:46
I would say a red cross is more likely to be used for an error. Green indicates something has been successfully done.

**Comment by ghost** [comment] 2021-05-11 10:45
I think that green tick should be for on, Red Cross should be for off, and yellow/orange explaination mark (!) should be for errors

**Comment by ghost** [comment] 2021-05-11 16:23
![image](https://user-images.githubusercontent.com/70704875/117850870-a3946680-b27d-11eb-857a-575db9c91e9f.png)
something like this

**Comment by 1zun4secondary** [comment] 2021-05-11 16:24
This looks so wrong. Of course, it makes sense to show something "red" when you turn off but ... I don't know. It doesn't fit.

**Comment by Cypphi** [comment] 2021-05-11 16:25
> ![image](https://user-images.githubusercontent.com/70704875/117850870-a3946680-b27d-11eb-857a-575db9c91e9f.png)
> something like this

i like that idea, exactly what i meant

**Comment by SenkJu** [comment] 2021-05-11 16:28
The problem is that notifications are intended to be as generic as possible. We want to use them for other things as well so adding specific icons for module toggle notifications would be a little strange.

**Comment by ghost** [comment] 2021-05-11 16:30
so are there only going to be ticks for icons?

**Comment by 1zun4secondary** [comment] 2021-05-11 16:33
No. There are other icons, but we probably won't use red-X icons for "Disabling module" which is basically a successful task (so it has to be Green)

**Comment by ghost** [comment] 2021-05-11 16:34
so a green cross?

**Comment by ghost** [comment] 2021-05-11 16:38
It must be a green cross whether the module is disabled or enabled. The `X` icon should be for errors, and the `!` icon should be for notification messages.

Examples:
`X`: Failed to load entities.
`!`: Speed module is disabled due to setback detection.

**Comment by ghost** [comment] 2021-05-11 16:40
what about icons being for what type of notification and colours for the status of that thing in the category?

**Comment by ghost** [comment] 2021-05-16 08:35
![image](https://user-images.githubusercontent.com/70704875/118391009-114be400-b62a-11eb-90e6-eb2095996187.png)
this is what i meant by the comment above btw

**Comment by ghost** [comment] 2021-05-16 08:37
so the colours are for what happened, and the icon is for the category of that thing (like binds, settings, modules ect)

**Comment by ghost** [comment] 2021-05-16 11:04
the icons dont need to be exactly like this, this is just showing off the idea

**Comment by Cypphi** [comment] 2021-05-16 12:27
> the icons dont need to be exactly like this, this is just showing off the idea

i think they look very good, i'd love if this got added

**Comment by ghost** [comment] 2021-05-16 13:37
> ![image](https://user-images.githubusercontent.com/70704875/118391009-114be400-b62a-11eb-90e6-eb2095996187.png)
> this is what i meant by the comment above btw

that looks so wrong

**Comment by ghost** [comment] 2021-05-16 14:08
what, the icons? like i said, its just showing off the idea, they dont have to look like this

**Comment by ghost** [comment] 2021-05-16 14:11
i mean, i personally like the icons, but thats just my opinion

**Comment by ghost** [comment] 2021-05-16 15:01
yeah i like the icons too, what they indicate is what i dont like.

**Comment by ghost** [comment] 2021-05-16 17:06
wdym?

**Comment by TheAwesome98-Real** [comment] 2021-05-31 06:07
> ![image](https://user-images.githubusercontent.com/70704875/118391009-114be400-b62a-11eb-90e6-eb2095996187.png)
> this is what i meant by the comment above btw

this looks cool, btw do you use gimp to edit cause i do too

**Comment by ghost** [comment] 2021-05-31 09:45
Thank you! And yes, I did

**Comment by ENDER1355** [comment] 2021-06-22 15:07
can we add @BobIsMyManager's one

**Comment by 1zun4secondary** [comment] 2021-06-22 18:01
No.

**Comment by ghost** [comment] 2021-06-22 19:31
So wait, why is this issue open then?

**Comment by TheAwesome98-Real** [comment] 2021-06-23 07:54
> No.

why

**Comment by ghost** [comment] 2021-06-23 09:38
> > No.
> 
> why

The icons don't really match its purpose.

**Comment by ghost** [comment] 2021-06-23 14:46
Like I said, the icons don’t have to be exactly the same, they were just an example 

> > > No.
> > 
> > 
> > why
> 
> The icons don't really match its purpose.

**Comment by TheAwesome98-Real** [comment] 2021-06-24 06:58
> > > No.
> > 
> > 
> > why
> 
> The icons don't really match its purpose.

https://en.wiktionary.org/wiki/example

**Comment by ENDER1355** [comment] 2021-06-24 10:04
> No.

close this crap then

**Comment by ENDER1355** [comment] 2021-06-24 12:18
> No.

i mean the one with a cube

**Comment by TheAwesome98-Real** [comment] 2021-06-24 15:03
> > No.
> 
> close this crap then

you get how not anyone can close a issue right? also you're like 5 shut up

**Comment by ghost** [comment] 2021-06-24 15:17
some people got things to do irl

**Comment by ENDER1355** [comment] 2021-06-24 16:09
> > > No.
> > 
> > 
> > close this crap then
> 
> you get how not anyone can close a issue right? also you're like 5 shut up

1zun4 has write access, meaning he can close it, we know, we are not stupid

**Comment by ghost** [comment] 2021-06-24 19:54
Only people with write access and the person who opened the issue can close it 

> > > No.
> > 
> > 
> > close this crap then
> 
> you get how not anyone can close a issue right? also you're like 5 shut up

**Comment by ENDER1355** [comment] 2021-06-25 20:29
> Only people with write access and the person who opened the issue can close it
> 
> > > > No.
> > > 
> > > 
> > > close this crap then
> > 
> > 
> > you get how not anyone can close a issue right? also you're like 5 shut up

i told the devs (people who have write access) to close it

**Comment by 1zun4secondary** [comment] 2021-06-25 20:39
We are not going to close this issue. This is still a design issue.
Logically is the current one correct, but it feels wrong somehow.

**Comment by ghost** [comment] 2021-06-25 20:41
^

**Comment by ghost** [comment] 2021-06-25 21:08
One method to solve this is to simply make a red version of the check mark, the background only.

EDIT: This is what I would prefer.

![Desktop Screenshot 2021 06 26 - 00 17 12 94 (2)](https://user-images.githubusercontent.com/70612656/123486111-19794500-d614-11eb-97a1-270743194609.png)

**Comment by ghost** [comment] 2021-06-26 08:44
As long as the enable colour is green, and the disable colour is red, I'm down

**Comment by ghost** [comment] 2021-06-26 09:53
Agreed. That's how it should be to be honest.

**Comment by ghost** [comment] 2021-06-26 12:20
I like the icons better buts that's probably just personal bias

**Comment by Cypphi** [comment] 2021-06-28 14:57
nah I like it as well, I think it makes sense to have different colors for disabling and enabling so its way easier to see if you enabled or disabled something without having to read the mf text

**Comment by TheAwesome98-Real** [comment] 2021-06-28 16:56
i like it too

**Comment by TheAwesome98-Real** [comment] 2021-06-28 16:57
> > > > No.
> > > 
> > > 
> > > close this crap then
> > 
> > 
> > you get how not anyone can close a issue right? also you're like 5 shut up
> 
> 1zun4 has write access, meaning he can close it, we know, we are not stupid

i said specifically you

**Comment by ENDER1355** [comment] 2021-06-28 19:22
> > > > > No.
> > > > 
> > > > 
> > > > close this crap then
> > > 
> > > 
> > > you get how not anyone can close a issue right? also you're like 5 shut up
> > 
> > 
> > 1zun4 has write access, meaning he can close it, we know, we are not stupid
> 
> i said specifically you

yea whatever

**Comment by ghost** [comment] 2021-06-28 19:24
> nah I like it as well, I think it makes sense to have different colors for disabling and enabling so its way easier to see if you enabled or disabled something without having to read the mf text

bro thats how disable and enable colors should be

**Comment by ghost** [comment] 2021-06-28 20:18
> > nah I like it as well, I think it makes sense to have different colors for disabling and enabling so its way easier to see if you enabled or disabled something without having to read the mf text
> 
> bro thats how disable and enable colors should be

That’s the reason this issue was opened in the first place lmao

**Comment by TheAwesome98-Real** [comment] 2021-06-29 08:45
> > > > > > No.
> > > > > 
> > > > > 
> > > > > close this crap then
> > > > 
> > > > 
> > > > you get how not anyone can close a issue right? also you're like 5 shut up
> > > 
> > > 
> > > 1zun4 has write access, meaning he can close it, we know, we are not stupid
> > 
> > 
> > i said specifically you
> 
> yea whatever

man stop acting like you aren't in the wrong here, we're just tryna discuss fucking notification colours lmao

**Comment by TheAwesome98-Real** [comment] 2021-06-29 09:11
wait i just thought of something: should disabling a module be a green 'x' or a red '✔'?

**Comment by ghost** [comment] 2021-06-29 09:17
?

**Comment by TheAwesome98-Real** [comment] 2021-06-29 09:33
green background with an x, or a red background with a ✔?

**Comment by ghost** [comment] 2021-06-29 09:39
Ok

**Comment by ghost** [comment] 2021-06-29 09:43
> green background with an x, or a red background with a ✔?

red background with a ✔

**Comment by TheAwesome98-Real** [comment] 2021-06-29 09:45
> > green background with an x, or a red background with a heavy_check_mark?
> 
> red background with a ✔

okay

**Comment by ghost** [comment] 2021-06-29 09:48
The colour is the part you need to know ASAP as you don’t need to look at it, you just see it out of the corner of your eye

**Comment by TheAwesome98-Real** [comment] 2021-06-29 09:50
true

**Comment by ENDER1355** [comment] 2021-06-29 13:49
> > green background with an x, or a red background with a ✔?
> 
> red background with a ✔

good

**Closed as completed** 2023-06-05 12:19 UTC
Labels: 🤷 unconfirmed, 🌑 nextgen
