### ISSUE TITLE
[BUG] timer range reset

### ISSUE THREAD

**Issue by hungrypotat** [CCBlueX/LiquidBounce#2674] opened 2024-03-30 20:23 UTC
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

b90 killaura f5

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

still when 10 tick plus sometimes it fails to reset anmd goes super high timer

### Steps to reproduce

turn timer raneg on 10 tick play for a bit abt 15 min then timer no reset insta ban

### Client Log

```shell
.
```

**Comment by EclipsesDev** [comment] 2024-03-31 05:56
yes i haven't fix it yet.. I'll look into it soon

**Comment by EclipsesDev** [comment] 2024-03-31 08:40
Alright fixed it, lemme know if it still happened.. i did test it and it worked, tho- I haven't fully tested it

**Comment by EclipsesDev** [comment] 2024-03-31 08:44
also try to tune/configured the timerCharged & timerBoost option correctly

**Comment by hungrypotat** [comment] 2024-03-31 11:01
not fixed still happened :/

**Comment by EclipsesDev** [comment] 2024-03-31 11:02
> not fixed still happened :/

yeah maybe u need to lower ur timercharge, try that, and maybe lower a bit ur timerboost

**Comment by hungrypotat** [comment] 2024-03-31 11:04
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/d5a5ca67-8eb2-4a22-9eec-aa4be7a1634a)
this fine?

**Comment by EclipsesDev** [comment] 2024-03-31 11:08
ur timerboost is to high lol, should at least be 4 or 7 thats should be enough, or for intave maybe lower.. thats prob why ur banned

**Comment by hungrypotat** [comment] 2024-03-31 11:09
lemme try that, cos before it worked fine

**Comment by hungrypotat** [comment] 2024-03-31 11:14
damn it works welp

**Comment by hungrypotat** [comment] 2024-03-31 11:20
never mind its weird but it just stays at high timer for some reason sometimes after taking kb  or summat

**Comment by hungrypotat** [comment] 2024-03-31 11:21
cos before this update only the 10 tick plus had this issue now 9 tick also has this issue

**Comment by EclipsesDev** [comment] 2024-03-31 11:23
u know what, send me ur config.. I'll test it

**Comment by hungrypotat** [comment] 2024-03-31 11:25
bruh moment
it doesnt always happen it could be 100% fine for a few matches then suddenly super flag timer
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/b32fcc4e-1d8e-4922-9412-81af5ef9965e)
also btw do u have dc lemme add u :)

**Comment by EclipsesDev** [comment] 2024-03-31 13:36
yeah still maybe lower ur timer to like 3 or 4, it could be that intave detect timer

**Comment by hungrypotat** [comment] 2024-03-31 15:27
nah bro i configed for a lil bit i found that u can go higher but u need to "match" the delays 
i just copied someones augustus timerrange seems fine ??

**Comment by hungrypotat** [comment] 2024-03-31 15:31
intave is weird

**Comment by hungrypotat** [comment] 2024-04-02 14:38
i got clip of the bug it only happens sometimes, but the config does work 100%

https://github.com/CCBlueX/LiquidBounce/assets/83085672/521b4c85-fab7-4bf0-8cdd-7e891c1f3f6d

**Comment by hungrypotat** [comment] 2024-04-02 14:40
@EclipsesDev

**Comment by EclipsesDev** [comment] 2024-04-02 14:41
ah def issue with the target selection thing.. I'll fix it (soon)

**Comment by EclipsesDev** [comment] 2024-04-08 13:00
> bruh moment it doesnt always happen it could be 100% fine for a few matches then suddenly super flag timer ![image](https://private-user-images.githubusercontent.com/83085672/318261415-b32fcc4e-1d8e-4922-9412-81af5ef9965e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODEyNjcsIm5iZiI6MTcxMjU4MDk2NywicGF0aCI6Ii84MzA4NTY3Mi8zMTgyNjE0MTUtYjMyZmNjNGUtMWQ4ZS00OTIyLTk0MTItODFhZjVlZjk5NjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyNTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0OTMwOTRmZWJhOTFiMTkwNTkzNmQ5YjFmMTdlYzkzMzJlYmNmZjg3MTc3YmI0MzViZjY4ZTRhNTg2NTVmMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4uvza9PBtGLLXKRcxDB_6rac5CSZga7MmcrbH5yv5jE) also btw do u have dc lemme add u :)

I use this config, and still i couldn't reproduce the same issue

**Comment by EclipsesDev** [comment] 2024-04-08 13:01
I even tried higher ticks like 10 - 20, still couldn't reproduce the same issue

**Comment by EclipsesDev** [comment] 2024-04-08 13:02
![Screenshot 2024-04-08 200227](https://github.com/CCBlueX/LiquidBounce/assets/99494277/38e66523-5ea0-4b9b-9c53-b2b6336a69ef)

**Comment by EclipsesDev** [comment] 2024-04-08 13:04
oh wait, the issue is caused by ur maxangledifference setting, somehow when u set it to low like 30 it will boost ur timer longer.. hmm ig i'll fix it

**Comment by hungrypotat** [comment] 2024-04-08 14:04
bruh

**Comment by hungrypotat** [comment] 2024-04-08 14:05
so just leave it high

**Comment by EclipsesDev** [comment] 2024-04-08 14:13
like 60 - 65 should be fine

**Comment by hungrypotat** [comment] 2024-04-08 14:14
ok btw the f5 issue is still not fixed in ka

**Comment by EclipsesDev** [comment] 2024-04-08 14:14
> ok btw the f5 issue is still not fixed in ka

send vid

**Comment by hungrypotat** [comment] 2024-04-08 14:18
https://github.com/CCBlueX/LiquidBounce/assets/83085672/15f8583d-2862-4630-a1b5-db2cd1cbbf72

here

**Comment by EclipsesDev** [comment] 2024-04-08 14:29
> i.mp4 
> here

I don't quite know what happened on the video, so could u explain whats wrong?

**Comment by hungrypotat** [comment] 2024-04-08 14:31
in killaura u know whenu go in f5 i have f5 mode disabled but it kicks me out of f5 mode

**Comment by EclipsesDev** [comment] 2024-04-09 00:27
ah ok, will be fix in next pull

**Comment by EclipsesDev** [comment] 2024-04-09 01:17
> ok btw the f5 issue is still not fixed in ka

fixed in #2748

**Comment by hungrypotat** [comment] 2024-04-09 17:19
fixed

**Comment by hungrypotat** [comment] 2024-04-09 17:19
what does stop range do cos it seems to just silent flag

**Comment by EclipsesDev** [comment] 2024-04-10 00:34
> what does stop range do cos it seems to just silent flag

it basically doesn't allow you to timer boost at the selected stop range

**Comment by EclipsesDev** [comment] 2024-04-10 00:35
I don't suggest using stoprange

**Comment by hungrypotat** [comment] 2024-04-28 13:00
when will the issue bye fixed?

**Comment by EclipsesDev** [comment] 2024-04-28 13:40
Will be fixed in b92 (I will try my best)

**Comment by EclipsesDev** [comment] 2024-05-01 10:55
Should be fixed in b92 latest nightly build

**Closed as completed by EclipsesDev** 2024-05-01 10:55 UTC
Labels: 🐛 bug, 🌕 legacy

**Comment by hungrypotat** [comment] 2024-05-01 17:27
it isnt fixed  ait stays fast timer sometimes but logic is better :/

**Comment by hungrypotat** [comment] 2024-05-01 17:30
it happens as i kill someone

**Comment by hungrypotat** [comment] 2024-05-01 17:30
mostly

**Comment by EclipsesDev** [comment] 2024-05-02 00:03
I'll fix it again later, i could fix it by old reset method, but it'll reset other timer too..

**Comment by hungrypotat** [comment] 2024-05-02 14:05
K cool

**Comment by EclipsesDev** [comment] 2024-05-05 08:39
ok wait I've fully fixed it

**Comment by hungrypotat** [comment] 2024-05-05 09:14
maybe not fixed ima send clip

**Comment by hungrypotat** [comment] 2024-05-05 09:19
https://github.com/CCBlueX/LiquidBounce/assets/83085672/c483cb2c-dcfe-47cf-b1be-0d4a094fb80d

**Comment by EclipsesDev** [comment] 2024-05-05 09:22
wtf, hmm can u send config? @hungrypotat

**Comment by hungrypotat** [comment] 2024-05-05 09:24
sure bro
![image](https://github.com/CCBlueX/LiquidBounce/assets/83085672/a0b7ec5a-43cc-4e8c-b999-e1b0aecb2cd5)

**Comment by EclipsesDev** [comment] 2024-05-05 09:25
ok nvm, after testing.. its still happened mb

**Comment by hungrypotat** [comment] 2024-05-05 09:25
O

**Comment by EclipsesDev** [comment] 2024-05-05 09:37
ok wait i think i fixed it

**Comment by EclipsesDev** [comment] 2024-05-05 09:40
@hungrypotat try again

**Comment by hungrypotat** [comment] 2024-05-05 09:50
ok

**Comment by hungrypotat** [comment] 2024-05-05 09:50
ngl finding this kinda funny

**Comment by hungrypotat** [comment] 2024-05-05 09:53
thjink its fixed gonna test a bit more

**Comment by EclipsesDev** [comment] 2024-05-05 10:26
> thjink its fixed gonna test a bit more

so its fixed right :] ?

**Comment by hungrypotat** [comment] 2024-05-05 11:17
yus :)

**Comment by EclipsesDev** [comment] 2024-05-05 11:27
noice 👍

**Comment by hungrypotat** [comment] 2024-05-05 15:35
never mind it happens very rarely but happens once in like 70 gamres

**Comment by EclipsesDev** [comment] 2024-05-05 15:39
> never mind it happens very rarely but happens once in like 70 gamres

Bruh.. ehh I'll look into it again ig tomorrow

**Comment by hungrypotat** [comment] 2024-05-05 15:39
its fine take u r time :)
