### ISSUE TITLE
[BUG] toggleModule events in ClickGui causes JS exceptions

### ISSUE THREAD

**Issue by nettnikl** [CCBlueX/LiquidBounce#584] opened 2021-07-20 18:34 UTC
### LiquidBounce Build/Version

nextgen

### Operating System

Linux

### Minecraft Version

1.17.1, ...

### Describe the bug

Game crashes as soon as one of the modules in the ClickGui is leftclicked. Opening and closing categories works, moving of them also. Just clicking the modules inside of the categories doesn't. This affects all modules. TabGui works.
The GL_INVALID_ENUM messages are unrelated and were printed during the last two render cycles.

### Steps to reproduce

- Open the game
- Enter a fresh sp world
- Bind the ClickGui
- Use the keybind to open the gui
- Open a category
- Click an item in the category

### Client Log

```shell
[20:29:17] [Render thread/INFO] (Minecraft) OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
[20:29:17] [Render thread/INFO] (Minecraft) OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
[20:29:17] [Render thread/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[20:29:17] [Render thread/FATAL] (Minecraft) Unreported exception thrown!
 com.labymedia.ultralight.javascript.JavascriptException: Error while calling javascript object as function
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1.invoke$lambda-1$lambda-0(UltralightJsEvents.kt:85) ~[main/:?]
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1$$Lambda$6715/0x000000009a5e4338.accept(Unknown Source) ~[?:?]
	at net.ccbluex.liquidbounce.render.ultralight.js.ViewContextProvider.syncWithJavascript(ViewContextProvider.kt:54) ~[main/:?]
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1.invoke$lambda-1(UltralightJsEvents.kt:84) ~[main/:?]
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1$$Lambda$6714/0x000000009a5e3fb0.execute(Unknown Source) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:179) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.14-v2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:166) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.14-v2.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:310) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.14-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1137) ~[minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.14-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:728) [minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.14-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [minecraft-1.17.1-project-@-mapped-net.fabricmc.yarn-1.17.1+build.14-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
[20:29:19] [Server thread/INFO] (Minecraft) Stopping server
[20:29:19] [Server thread/INFO] (Minecraft) Saving players
[20:29:19] [Server thread/INFO] (Minecraft) Player611 lost connection: Server closed
[20:29:19] [Server thread/INFO] (Minecraft) Player611 left the game
[20:29:19] [Server thread/INFO] (Minecraft) Stopping singleplayer server as player logged out
[20:29:19] [Server thread/INFO] (Minecraft) Saving worlds
[20:29:19] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[20:29:19] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[20:29:19] [Server thread/INFO] (Minecraft) Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[20:29:19] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (New World): All chunks are saved
[20:29:19] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:29:19] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:29:19] [Server thread/INFO] (Minecraft) ThreadedAnvilChunkStorage: All dimensions are saved
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 20.07.21, 20:29
Description: Unexpected error

com.labymedia.ultralight.javascript.JavascriptException: Error while calling javascript object as function
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1.invoke$lambda-1$lambda-0(UltralightJsEvents.kt:85)
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1$$Lambda$6715/0x000000009a5e4338.accept(Unknown Source)
	at net.ccbluex.liquidbounce.render.ultralight.js.ViewContextProvider.syncWithJavascript(ViewContextProvider.kt:54)
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1.invoke$lambda-1(UltralightJsEvents.kt:84)
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1$$Lambda$6714/0x000000009a5e3fb0.execute(Unknown Source)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:166)
	at net.minecraft.client.util.Window.swapBuffers(Window.java:310)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1137)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1.invoke$lambda-1$lambda-0(UltralightJsEvents.kt:85)
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1$$Lambda$6715/0x000000009a5e4338.accept(Unknown Source)
	at net.ccbluex.liquidbounce.render.ultralight.js.ViewContextProvider.syncWithJavascript(ViewContextProvider.kt:54)
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1.invoke$lambda-1(UltralightJsEvents.kt:84)
	at net.ccbluex.liquidbounce.render.ultralight.js.bindings.UltralightJsEvents$on$eventHook$1$$Lambda$6714/0x000000009a5e3fb0.execute(Unknown Source)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:166)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player611'/237, l='ClientLevel', x=-2.49, y=80.00, z=-4.86]]
	Chunk stats: 625, 397
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,68,-64), Section: (at 0,4,0 in -3,4,-4; chunk contains blocks -48,0,-64 to -33,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 735280 game time, 735280 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2399)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.11
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 16 Linux amd64-64-Bit Compressed References 20210421_23 (JIT enabled, AOT enabled)
OpenJ9   - b4cc246d9
OMR      - 162e6f729
JCL      - cea22090ecf based on jdk-16.0.1+9), Eclipse OpenJ9
	Memory: 750174712 bytes (715 MiB) / 1892810752 bytes (1805 MiB) up to 4173070336 bytes (3979 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 3,50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: GM204 [GeForce GTX 970]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288,00
	Graphics card #0 deviceId: 0x13c2
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7959,54
	Virtual memory used (MB): 11067,61
	Swap memory total (MB): 0,00
	Swap memory used (MB): 0,00
	JVM Flags: 4 total; -Xoptionsfile=/usr/lib/jvm/adoptopenjdk-16-openj9-amd64/lib/options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:+ShowCodeDetailsInExceptionMessages
	Fabric Mods: 
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab612118
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		java: Eclipse OpenJ9 VM 16
		liquidbounce: LiquidBounce 1.0.0
		minecraft: Minecraft 1.17.1
		multiconnect: MultiConnect 1.4.5
		multiconnect-api: MultiConnect API 1.4.5
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 970/PCIe/SSE2 GL version 3.2.0 NVIDIA 465.31, NVIDIA Corporation
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.' x 3352
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
	Player Count: 1 / 8; [ServerPlayerEntity['Player611'/237, l='ServerLevel[New World]', x=-2.49, y=80.00, z=-4.86]]
	Data Packs: vanilla, Fabric Mods
#@!@# Game crashed! Crash report saved to: #@!@# /home/username/IntelliJProjects/LiquidBounce/run/./crash-reports/crash-2021-07-20_20.29.20-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 255
```

**Comment by 1zun4secondary** [comment] 2021-07-20 18:40
This issue seems to be related to https://github.com/CCBlueX/LiquidBounce/commit/6adc2d0df6a1058da2881deebed4a0909bb062d8. I will make further investigation about this issue later.

**Comment by vladistev** [comment] 2021-07-27 15:34
Can reproduce on a windows 10 machine, 1.17.1, 264bc4c

**Comment by 1zun4secondary** [comment] 2021-07-29 09:21
This issue is caused by registering the toggleModule event on each panel.
https://github.com/CCBlueX/LiquidBounce-GUI/blob/3e4167c1bb81b3a5de539707b943fd18eb063964/clickgui/src/clickgui/Panel.svelte#L69

@SenkJu 

At least I added error handling to prevent crashes on mistakes
https://github.com/CCBlueX/LiquidBounce/commit/1ef6c6ef6f88dbd88e43ff894fe5f5ca4fca266c

**Comment by mems01** [comment] 2021-08-06 14:51
Fixed by this [commit.](https://github.com/CCBlueX/LiquidBounce-GUI/commit/86c0b808e486f20070ce2d95814afad5e66cf7b1)

**Closed as completed** 2023-02-19 12:40 UTC
Labels: 🐛 bug, 👷 development build, 🌑 nextgen
