### ISSUE TITLE
[BUG] Liquidbounce crashing on start

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#573] opened 2021-07-13 20:16 UTC
### LiquidBounce Build/Version

nextgen

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Describe the bug

When i start, it crashes when it's starting, and it returns this JVM crash:
[hs_err_pid3016.log](https://github.com/CCBlueX/LiquidBounce/files/6811714/hs_err_pid3016.log)
### Steps to reproduce

Start liquidbounce

### Client Log

```shell
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.labymedia.ultralight.UltralightRenderer.render()V+0
j  net.ccbluex.liquidbounce.render.ultralight.UltralightEngine.render(Lnet/ccbluex/liquidbounce/render/ultralight/RenderLayer;)V+16
j  net.minecraft.class_425.handler$zep000$hookSplashRender(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V+96
j  net.minecraft.class_425.method_25394(Lnet/minecraft/class_4587;IIF)V+20
j  net.minecraft.class_757.method_3192(FJZ)V+698
j  net.minecraft.class_310.method_1523(Z)V+358
j  net.minecraft.class_310.method_18098(Lnet/minecraft/class_437;)V+36
j  net.minecraft.class_310.method_18096(Lnet/minecraft/class_437;)V+47
j  net.minecraft.class_310.method_1519()V+60
j  net.minecraft.class_310.method_1514()V+160
j  net.minecraft.client.main.Main.main([Ljava/lang/String;)V+1366
v  ~StubRoutines::call_stub
j  sun.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0
j  sun.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100
J 2012 C1 sun.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (10 bytes) @ 0x0000024b209bbe4c [0x0000024b209bbd40+0x10c]
J 2013 C1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; (62 bytes) @ 0x0000024b20e4bd74 [0x0000024b20e4b980+0x3f4]
j  net.fabricmc.loader.game.MinecraftGameProvider.launch(Ljava/lang/ClassLoader;)V+71
j  net.fabricmc.loader.launch.knot.Knot.launch(Ljava/lang/ClassLoader;)V+23
j  net.fabricmc.loader.launch.knot.KnotClient.main([Ljava/lang/String;)V+39
v  ~StubRoutines::call_stub
```

**Comment by ghost** [comment] 2021-07-13 20:45
Windows 11 might not be supported yet on LiquidBounce nextgen.

**Comment by NurMarvin** [comment] 2021-07-13 21:01
Seems to be a duplicate of #547. Try installing a more recent Java version, more specifically Java 11 or higher.
You can find downloads for those here: https://adoptopenjdk.net/
I'll be closing this for now, but if this didn't solve the issue, feel free to let me know so I can re-open it to keep further track of the issue.

**Closed as completed by NurMarvin** 2021-07-13 21:01 UTC
Labels: 🐛 bug, 👯 duplicate, 👷 development build, 🌑 nextgen

**Comment by ghost** [comment] 2021-07-13 23:07
I was using java 15

**Comment by NurMarvin** [comment] 2021-07-13 23:11
> I was using java 15

According to the crash report, you were using Java Version 1.8.0_291-b10, which is Java 8.

**Comment by ghost** [comment] 2021-07-13 23:12
i think the minecraft launcher is forcing to use java 8 or something

**Comment by ghost** [comment] 2021-07-13 23:14
no, im dumb, i made sym link of java 8 to java 15, nvm
i dont remember of doing this, but, yeah, i'll say if it works

**Comment by ghost** [comment] 2021-07-13 23:20
![image](https://user-images.githubusercontent.com/36360774/125537319-0d2ad118-0dc9-4c9c-bbe2-16564d28568a.png)
this error with java 15

**Comment by ghost** [comment] 2021-07-13 23:23
i think its an JNI compatibility issue

**Comment by ghost** [comment] 2021-07-13 23:28
also happens with java 16 @NurMarvin

**Comment by ghost** [comment] 2021-07-13 23:53
openJDK 11, nothing

**Comment by NurMarvin** [comment] 2021-07-13 23:56
Have a look at the related issue I linked. You need to delete the JavaCheck.jar in the Minecraft Launcher's `game` directory.

**Comment by ghost** [comment] 2021-07-14 00:07
hmm, ok I'll do that
sorry for the delay, my mouse was moving by itself, like my computer was being Hacked or something, im not joking

**Comment by ghost** [comment] 2021-07-14 00:18
YAY IT WORKED, THX
