### ISSUE TITLE
[FEATURE] Nextgen Chams Module

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#2356] opened 2024-03-12 01:59 UTC
### LiquidBounce Branch

Nextgen

### Describe your feature request.

chams module from legacy to nextgen (or recode idk)

**Comment by superblaubeere27** [comment] 2024-03-12 02:32
Duplicate of #2081

**Closed as not planned by superblaubeere27** 2024-03-12 02:32 UTC
Labels: 👯 duplicate, 🔥 enhancement, 👷 development build, 🌑 nextgen
