### ISSUE TITLE
[FEATURE] KillAura-->NotDuringScaffold

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2686] opened 2024-03-31 15:40 UTC
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Pauses killaura when scaffold is on to prevent you from getting flagged by the anticheat.

**Comment by liquidsquid1** [comment] 2024-03-31 16:02
Duplicate of #2588 
Please don't spam duplicate reports, if it gets denied on the first one, it doesn't give you a right to keep begging.

**Comment by guosic** [comment] 2024-04-01 03:07
Increase the value of Scaffold TicksUntilReset, for example, input ".value Scaffold TicksUntilReset 30".

**Closed** 2024-04-01 07:16 UTC
Labels: 🔥 enhancement, 👷 development build, 🌑 nextgen
