### ISSUE TITLE
Unstable Criticals performance

### ISSUE THREAD

**Issue by sysdefense1337** [CCBlueX/LiquidBounce#1946] opened 2024-01-30 21:51 UTC
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.1.3

### Operating System

Windows 10

### Minecraft Version

1.9-1.20.4

### Describe the bug

Count how many crits I did. 
https://www.youtube.com/watch?v=WuSFVHNPWvc

### Steps to reproduce

Criticals with Jump mode.

### Client Log

```shell
-
```

### Screenshots

-

**Comment by fineless71** [comment] 2024-01-30 22:15
Dupe of #1897?

**Comment by sysdefense1337** [comment] 2024-01-30 22:16
> Dupe of #1897?

?

**Comment by fineless71** [comment] 2024-01-30 22:22
> > Dupe of #1897?
> 
> ?

I was saying that I think this problem has already been reported, from their issue:
> hello, criticals with "jump" mode enabled, hits once every 2-3 jumps. Although it should be once in 1 jump

Or are you saying something different?

**Comment by sysdefense1337** [comment] 2024-01-30 22:24
> > > Dupe of #1897?
> > 
> > 
> > ?
> 
> I was saying that I think this problem has already been reported, from their issue:
> 
> > hello, criticals with "jump" mode enabled, hits once every 2-3 jumps. Although it should be once in 1 jump
> 
> Or are you saying something different?

Yes, it's the same issue, I haven't seen this. But #1897 is empty.

**Comment by larryngton** [comment] 2024-01-31 13:45
criticals atm only work well with 1.8 combat

**Comment by sysdefense1337** [comment] 2024-01-31 14:49
> criticals atm only work well with 1.8 combat

that's true) but it should be made in the future, I think.

**Comment by superblaubeere27** [comment] 2024-01-31 23:13
~~Please send me your config so I can replicate the issue.~~


> criticals atm only work well with 1.8 combat

In the past jump crits worked great even for 1.9+ combat

**Comment by superblaubeere27** [comment] 2024-01-31 23:34
I was able to replicate and track down the issue.

**Comment by superblaubeere27** [comment] 2024-02-01 00:24
The issue was the missconfigured KillAura default `CooldownRange`. Change it to `1.0..1.0`

**Comment by sysdefense1337** [comment] 2024-02-01 11:24
@superblaubeere27 but it always loaded by default cooldown range 1-1 (now it's timing). Here is the new video with criticals.
https://www.youtube.com/watch?v=fRy4JKmv0Ko

**Comment by sysdefense1337** [comment] 2024-02-01 11:49
> @superblaubeere27 but it always loaded by default cooldown range 1-1 (now it's timing). Here is the new video with criticals. https://www.youtube.com/watch?v=fRy4JKmv0Ko

In my opinion, it should be like this. https://www.youtube.com/watch?v=m-MbAsC2XT0 

https://www.youtube.com/watch?v=m6GAm0KGOsI

**Comment by superblaubeere27** [comment] 2024-02-01 13:43
> @superblaubeere27 but it always loaded by default cooldown range 1-1 (now it's timing). Here is the new video with criticals. https://www.youtube.com/watch?v=fRy4JKmv0Ko

I watched the video. Note that the first hit is not a crit. This is an intended bug. When the other player comes into just a bit in our range we don't care about waiting for the crit since we want to do the first hit.

There are other situations where the client actively decides against waiting for a crit, because it deems that waiting for it will result in less DPS.

This [situation](https://youtu.be/fRy4JKmv0Ko?feature=shared&t=35) on the other hand shows a clear mistake which should not happen. I found 3 (of 40) hits in your video where I think the module has made a bad decision. This is rate of <10%, but I will reopen the issue and investigate further.

**Comment by sysdefense1337** [comment] 2024-02-01 14:40
> I watched the video. Note that the first hit is not a crit. This is an intended bug. When the other player comes into just a bit in our range we don't care about waiting for the crit since we want to do the first hit.
> 
> There are other situations where the client actively decides against waiting for a crit, because it deems that waiting for it will result in less DPS.
> 
> This [situation](https://youtu.be/fRy4JKmv0Ko?feature=shared&t=35) on the other hand shows a clear mistake which should not happen. I found 3 (of 40) hits in your video where I think the module has made a bad decision. This is rate of <10%, but I will reopen the issue and investigate further.


I mean that against players (in some duels at 1.9 hvh) I will have less chances, because crits sometimes really don’t work, it would be nice if it weren’t such a thing that a person can hit 2-3 times without a crit (this is due to the fact that the killaura hits when it jumps, but it needs to hit when falling, this is the fall distance), and then all the crits will go well like in this video from Akrien (and I can fight against hackers on the duel hvh server, tried with LB but loss.), I showed the killaura settings here, because Jump Criticals is a separate checkbox in killaura, and not a mode in criticalals. https://www.youtube.com/watch?v=m6GAm0KGOsI

**Comment by sysdefense1337** [comment] 2024-02-01 14:45
If you want, I can record the video from the hvh server, where I will fight against other hacker. I will play with LiquidBounce Nextgen and Akrien. (1.9 pvp). The problem itself is the difference in crits.

**Comment by superblaubeere27** [comment] 2024-02-01 16:01
I know that the problem is that KillAura hits when jumping instead of falling haha. It is the underlying util that tells KillAura that it makes no sense to wait for the falling phase when it really does.

I think the problem is that we are using falling player which the wrong tool to approximating how long the player is going to be airbound. I will improve the simulation quality which should fix the issue.

**Comment by sysdefense1337** [comment] 2024-02-01 16:05
> I know that the problem is that KillAura hits when jumping instead of falling haha. It is the underlying util that tells KillAura that it makes no sense to wait for the falling phase when it really does.
> 
> I think the problem is that we are using falling player which the wrong tool to approximating how long the player is going to be airbound. I will improve the simulation quality which should fix the issue.

I played against unsofter (on hvh server 0% chance lol) with LB. Played with Akrien against hacker. First media it's liquidbounce, second is akrien. Compare the crits work. https://www.youtube.com/watch?v=T-JQbjzClgI

**Comment by sysdefense1337** [comment] 2024-02-01 16:12
you know, such a moment, it may not crit when I move, but when I stand, it crits normally (sometimes)

**Comment by superblaubeere27** [comment] 2024-02-01 23:58
Seems to be fixed now. https://youtu.be/MkQqUFKXPfo

Btw, if you use legit hop + OptimizeForCriticals + Criticals with mode NONE, you will get a much nicer experience in PvP.

Thank you for your useful feedback and please come back to us if the issue still persists or you find another issue :)

**Closed as completed** 2024-02-02 00:03 UTC
Labels: 🐛 bug, 👷 development build, 🌑 nextgen

**Comment by sysdefense1337** [comment] 2024-02-02 00:56
> Seems to be fixed now. https://youtu.be/MkQqUFKXPfo
> 
> Btw, if you use legit hop + OptimizeForCriticals + Criticals with mode NONE, you will get a much nicer experience in PvP.
> 
> Thank you for your useful feedback and please come back to us if the issue still persists or you find another issue :)

Thank you, criticals are working well now.) Problem was fixed.
