### ISSUE TITLE
[BUG] Velocity having no effect

### ISSUE THREAD

**Issue by joaopinto24** [CCBlueX/LiquidBounce#4161] opened 2024-10-14 01:24 UTC
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

0.15.1

### Operating System

Windows 10

### Minecraft Version

1.21.1

### Describe the bug

Turning on the module on modify isn't working, I have everything on 0.  IIRC it was working fine in 0.15.0

### Steps to reproduce

Open ClickGui, turn on velocity, change to a value where you notice the difference.

### Client Log

```shell
Irrelevant, checked the logs and nothing came up
```

**Comment by 1zun4** [comment] 2024-10-14 06:27
This has been fixed in the development versions already. It is caused by the "Pause on Flag" option, when triggered once, it stays active forever.

**Closed as completed by 1zun4** 2024-10-14 06:27 UTC
Labels: 🐛 bug, 🌑 nextgen
