### ISSUE TITLE
[FEATURE] Chams Module

### ISSUE THREAD

**Issue by 7n7e7o7** [CCBlueX/LiquidBounce#2608] opened 2024-03-25 16:41 UTC
### LiquidBounce Branch

Nextgen

### Describe your feature request.

chams module like in legacy

**Comment by liquidsquid1** [comment] 2024-03-25 19:02
Duplicate of #2081 
Can this be closed

**Comment by superblaubeere27** [comment] 2024-03-25 20:25
As @liquidsquid1 said, there is already an issue with that topic.

But we are working on it, so you can expect the module in the next few versions :)

**Closed as not planned** 2024-03-25 20:25 UTC
Labels: 👯 duplicate
