### ISSUE TITLE
[FEATURE] external gui because it looks cool

### ISSUE THREAD

**Issue by makerio90** [CCBlueX/LiquidBounce#354] opened 2021-02-23 04:42 UTC
**Describe your feature request.**
external gui look really cool, it would be nice to add one.
i can also pretend i got a ghost client
it wont have an actual purpose

**Comment by NurMarvin** [comment] 2021-02-23 07:04
Duplicate of #345. You are still not going to get it.

**Closed by NurMarvin** 2021-02-23 07:04 UTC
