### ISSUE TITLE
[BUG] search bug

### ISSUE THREAD

**Issue by larryngton** [CCBlueX/LiquidBounce#1742] opened 2023-12-26 16:29 UTC
### LiquidBounce Branch

Nextgen

### LiquidBounce Build/Version

git-d31c0d7

### Operating System

Windows 11

### Minecraft Version

1.20.4

### Describe the bug

yeah idk

### Steps to reproduce

open the clickgui
search for a module
close the clickgui
bug

### Client Log

```shell
.
```

**Comment by 1zun4** [comment] 2023-12-26 17:05
Please make a video. I am not able to reproduce this issue.

**Comment by larryngton** [comment] 2023-12-26 19:12
> Please make a video. I am not able to reproduce this issue.

it will take months to upload, but sure

**Comment by larryngton** [comment] 2023-12-26 19:13
c0c6269

> > Please make a video. I am not able to reproduce this issue.
> 
> it will take months to upload, but sure

c0c6269 probably fixed it though

**Comment by larryngton** [comment] 2023-12-26 19:22
turns out it got fixed, lmao

**Comment by larryngton** [comment] 2023-12-26 19:34
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/02205b01-da91-42f6-b069-f8bd8df097aa)
IT DIDNT GET FIXED AND I TOGGLED SPRINT TWICE

**Comment by larryngton** [comment] 2023-12-26 19:34
it just happens randomly

**Comment by larryngton** [comment] 2023-12-26 19:39
> ![image](https://private-user-images.githubusercontent.com/143325613/292912423-02205b01-da91-42f6-b069-f8bd8df097aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTk4NTIsIm5iZiI6MTcwMzYxOTU1MiwicGF0aCI6Ii8xNDMzMjU2MTMvMjkyOTEyNDIzLTAyMjA1YjAxLWRhOTEtNDJmNi1iMDY5LWY4YmQ4ZGYwOTdhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxOTM5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTQxOGRlODRlZjk1NWNkZGRhNjNkZmMyYzg3ZGM2ZTljYjI1NDA0MDc0NmEzMzc1ZmJmZDViNDNmYjIzNzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UEoBWwkW-9cK1US3omcG8l61WKUYmFBW5aPtufi0kxs) IT DIDNT GET FIXED AND I TOGGLED SPRINT TWICE

update: scaffold also gets toggled now

**Comment by larryngton** [comment] 2023-12-26 19:48
![image](https://github.com/CCBlueX/LiquidBounce/assets/143325613/0c8f6bbc-cf84-45fd-9a19-2cf0ec7b5cb4)
OH MY

**Comment by larryngton** [comment] 2023-12-26 20:32
> Please make a video. I am not able to reproduce this issue.

turns out it was the search fucking things up

**Comment by SenkJu** [comment] 2023-12-26 20:34
Can you please use the edit feature to add additional context to the original issue instead of posting dozens of comments? This isn't Discord. We receive an E-Mail notification for every single comment you post.

**Comment by 1zun4** [comment] 2023-12-26 23:17
should be fixed

**Closed by 1zun4** 2023-12-26 23:17 UTC
Labels: 🐛 bug, 👷 development build, 🌑 nextgen
