### ISSUE TITLE
[FEATURE] Animations-->SwingAnimations, SlowdDown

### ISSUE THREAD

**Issue by Anonimouze** [CCBlueX/LiquidBounce#2723] opened 2024-04-03 12:45 UTC
### LiquidBounce Branch

Nextgen

### Describe your feature request.

Add options in the Animations module that will allow the users to choose the swing animations and apply slowdown to animations features. Here are my suggestions:
* SwingAnimations: This option would allow us to choose Swing Animations according to our preferences. There should be some basic choices for this option such as 'Default' and 'Smooth'. This is will be particularly useful for the 1.9+ servers as in the latest versions of Minecraft, its very difficult to see the hand swing because of the attack cooldown feature especially with small weapons resource packs. So it would be better for us to have another kind of swing animation. 
* SlowDown: This option would make it possible to apply slow down to all kinds of animations. This will also make the animations look nicer.

**Comment by Anonimouze** [comment] 2024-04-03 12:45
Heres how the Swing Animation should be:

Uploading SwingAnimation.mp4…

**Comment by Anonimouze** [comment] 2024-04-03 12:46
Heres how the swing animation should be: 

https://github.com/CCBlueX/LiquidBounce/assets/146366549/9efdd839-a319-47e6-be01-22c4288c1b15

**Comment by liquidsquid1** [comment] 2024-04-03 13:06
Duplicate of #2450

**Closed** 2024-04-03 13:54 UTC
Labels: 🔥 enhancement, 👷 development build, 🌑 nextgen

**Comment by Anonimouze** [comment] 2024-04-03 13:57
> Duplicate of #2450

Huh? Only 1 thing is duplicate
