### ISSUE TITLE
[BUG]Teams doesnt work

### ISSUE THREAD

**Issue by Husky272** [CCBlueX/LiquidBounce#4750] opened 2024-11-29 14:54 UTC
### LiquidBounce Branch

Legacy

### LiquidBounce Build/Version

latest

### Operating System

Windows 10

### Minecraft Version

1.8.9

### Describe the bug

https://www.bilibili.com/video/BV1yAzrY8EWJ/

### Steps to reproduce

not sure,seems only happen when teammates respawn

### Client Log

```shell
no
```

**Comment by Husky272** [comment] 2024-11-29 15:02
Test in 163mc.cn experience bedwars

**Comment by EclipsesDev** [comment] 2024-12-01 13:43
I cannot reproduce the same issue

**Comment by Husky272** [comment] 2024-12-01 22:47
InputFix and LB

**Comment by Husky272** [comment] 2024-12-01 22:48
> I cannot reproduce the same issue

It sometimes happen
sometimes not，I dont know whats going wrong

**Comment by ghost** [comment] 2024-12-01 22:55
Make sure the issue still persists without the InputFix mod.

**Comment by EclipsesDev** [comment] 2024-12-03 09:22
well we can't do anything about this unless u provide log when that happens

**Comment by EclipsesDev** [comment] 2024-12-03 09:22
also it might be antibot but i might be wrong

**Comment by EclipsesDev** [comment] 2024-12-03 09:30
ok nvm after looking at ur issue from #4747 i can see why

**Comment by EclipsesDev** [comment] 2024-12-03 09:31
it seems to causes issue in pointeresp too due to `Teams.isInYourTeam` being used there

**Comment by EclipsesDev** [comment] 2024-12-03 09:32
but it should be fixed now

**Closed as completed** 2024-12-03 09:34 UTC
Labels: 🐛 bug, 🤷 unconfirmed, 🌕 legacy
