### ISSUE TITLE
[BUG] AutoArmor and InventoryCleaner Dont Working

### ISSUE THREAD

**Issue by Vatech1608** [CCBlueX/LiquidBounce#262] opened 2020-11-14 10:54 UTC
AutoArmor dont wearing armor and inventorycleaner it doesnt clean, it cleans the armor while cleaning.

1. Open AutoArmor or InventoryCleaner when in game
2. See error

 - OS: Windows 10
 - Latest LiquidBounce Build Version
 - Minecraft Version 1.8.9

**Comment by Teals53** [comment] 2020-11-14 16:44
yeah common problem and still not fixed around 3 month xD

**Comment by NurMarvin** [comment] 2020-11-14 23:37
Duplicate of #234. Please make sure to check for open issues regarding those kind of things before opening new issues.

**Closed by NurMarvin** 2020-11-14 23:37 UTC
