### ISSUE TITLE
[BUG] fix mixin injections not working in launcher environment

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce#467] opened 2021-05-06 18:07 UTC
When I tried it a few months ago and latest it just crashes when I attempt to start it:
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2246.<clinit>(class_2246.java:99)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458$$Lambda$189/452364286.get(Unknown Source)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at net.minecraft.class_5458$$Lambda$197/1685407532.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector hookStrideGround(Lnet/minecraft/class_1657;)Z in liquidbounce.mixins.json:minecraft.entity.MixinPlayerEntity failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap liquidbounce-refmap.json

I have kotlin language and the latest fabric loader 1.16.5. I'm assuming the next-gen version doesn't support 1.16.5?

**Comment by SenkJu** [comment] 2021-05-06 18:08
It does support Minecraft 1.16.5. Maybe @superblaubeere27 can have a look at this issue.

**Comment by superblaubeere27** [comment] 2021-05-06 18:49
Are you using any other mods with LiquidBounce?

**Comment by 1zun4secondary** [comment] 2021-05-06 18:52
this is my fucky wucky. I'll fix it as soon as possible. It is becuase of the Stirde Event injection. There might be a few differences to the vanilla jar which causes the redirect to fail.

**Comment by 1zun4secondary** [comment] 2021-05-08 22:18
should be fixed now
https://github.com/CCBlueX/LiquidBounce/commit/3a8f0d736c14f209c74fe07d2305a2e3b660e251

**Comment by Teals53** [comment] 2021-05-09 14:31
[17:30:29] [main/INFO]: Loading for game Minecraft 1.16.5
[17:30:30] [main/INFO]: [FabricLoader] Loading 13 mods: org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, minecraft@1.16.5, org_jetbrains_kotlin_kotlin-reflect@1.4.31, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, liquidbounce@1.0.0, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, java@8, fabric-language-kotlin@1.5.0+kotlin.1.4.31, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2
[17:30:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Pc/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[17:30:36] [main/INFO]: [STDERR]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[17:30:36] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
[17:30:36] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
[17:30:36] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
[17:30:36] [main/INFO]: [STDERR]: Caused by: java.lang.reflect.InvocationTargetException
[17:30:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:30:36] [main/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:30:36] [main/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:30:36] [main/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[17:30:36] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
[17:30:36] [main/INFO]: [STDERR]: 	... 2 more
[17:30:36] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[17:30:36] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[17:30:36] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
[17:30:36] [main/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[17:30:36] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:185)
[17:30:36] [main/INFO]: [STDERR]: 	... 7 more
[17:30:36] [main/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector hookSprintAffect(Lnet/minecraft/class_746;)Z in liquidbounce.mixins.json:minecraft.entity.MixinClientPlayerEntity failed injection check, 3 succeeded of 2 allowed.
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:413)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[17:30:36] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[17:30:36] [main/INFO]: [STDERR]: 	... 14 more

**Comment by Teals53** [comment] 2021-05-09 14:31
no

**Comment by Teals53** [comment] 2021-05-09 14:33
damn why i cant copy the log

**Comment by 1zun4secondary** [comment] 2021-05-09 14:56
that's another issue.

**Comment by Teals53** [comment] 2021-05-09 14:56
im still cant launch the game :p

**Comment by 1zun4secondary** [comment] 2021-05-09 15:01
yeah I know. It's annoying. I'll probably just ignore this in the future, until nextgen is about to get a offical release. As long it works in the IDE. Somehow Mixin has issues with the mappings which causes such errors and somehow the code being different, not sure why.

**Comment by Teals53** [comment] 2021-05-09 15:03
so we need to wait until the first release before try to use that into launcher

**Comment by 1zun4secondary** [comment] 2021-05-09 15:03
Yes.

**Comment by 1zun4secondary** [comment] 2021-05-09 15:04
There is also no remapper for the JS engine of ultralight and ScriptAPI. It is still not ready to be used in the obfuscated environment.

**Comment by Teals53** [comment] 2021-05-09 15:05
rip

**Comment by Teals53** [comment] 2021-05-09 15:05
how it can be take long to be ready for try it on launcher.

**Comment by 1zun4secondary** [comment] 2021-05-09 15:06
why should you try it. It is not done at all.

**Comment by Teals53** [comment] 2021-05-09 15:07
idk i just wanna try for see whats new about next gen like i did it a few weeks ago but now its broken for launcher environment :p

**Comment by 1zun4secondary** [comment] 2021-05-10 21:23
fixed

**Closed as completed by 1zun4secondary** 2021-05-10 21:23 UTC
Labels: 🐛 bug, 👷 development build, 🌑 nextgen

**Comment by 1zun4secondary** [comment] 2021-05-10 21:25
![cd3eGY7zYg](https://user-images.githubusercontent.com/69533520/117726500-f2db8800-b1e6-11eb-9590-f801c97ed8d8.png)
