### ISSUE TITLE
[FEATURE] backtrack

### ISSUE THREAD

**Issue by MikosLeftThigh** [CCBlueX/LiquidBounce#1476] opened 2023-10-29 16:02 UTC
### LiquidBounce Branch

Nextgen

### Describe your feature request.

abuse latency to give you a reach advantage

**Comment by Ell1ott** [comment] 2023-10-29 16:44
Isn't this a duplicate of #1411 ?

**Closed** 2023-10-29 17:10 UTC

**Comment by MikosLeftThigh** [comment] 2023-10-29 19:42
> Isn't this a duplicate of #1411 ?

i thought you forgor
