### ISSUE TITLE
[BUG] MainMenu cannot display (maybe)

### ISSUE THREAD

**Issue by hax0r31337** [CCBlueX/LiquidBounce#571] opened 2021-07-12 02:37 UTC
### LiquidBounce Build/Version

324f46a

### Operating System

Linux

### Minecraft Version

1.16.4

### Describe the bug

I cant see any thing after client launched,but the game is still running(BGM plays)

### Steps to reproduce

Launch the client with HMCL
and cant see any thing

### Client Log

```shell
https://paste.ccbluex.net/646240266
```

### Screenshots

![image](https://user-images.githubusercontent.com/65506006/125222585-dd74fe00-e2fc-11eb-8307-5b8bc5f6491f.png)

**Comment by ghost** [comment] 2021-07-12 07:25
> ### Operating System
> Linux

Linux is not supported as of now, it will be by the time the client is done

> ### Minecraft Version
> 1.16.4

the current branch in on 1.16.5, not 1.16.4

**Comment by NurMarvin** [comment] 2021-07-12 11:19
Duplicate of #424

**Closed as completed by NurMarvin** 2021-07-12 11:19 UTC
Labels: 👯 duplicate
