### ISSUE TITLE
[BUG] Tracers not working

### ISSUE THREAD

**Issue by NoOrMaLN** [CCBlueX/LiquidBounce#247] opened 2020-10-12 11:06 UTC
**Describe the bug**
when i turn on tracers it glitches and sends this msg
OpenGL Error: 1282 (invalid operation)

**To Reproduce**
1. Turn on NameTags
2. Turn on tracers
3. Drop any item

**Screenshots**
![2020-10-11_18 36 46](https://user-images.githubusercontent.com/72738564/95739500-3be84f80-0c8b-11eb-9b3d-5b38b7ac587d.png)

and it will looks like this when NameTags is off
![2020-10-12_12 48 03](https://user-images.githubusercontent.com/72738564/95739665-76ea8300-0c8b-11eb-8011-2b45575bb848.png)

**Additional information:**
 - OS: [windows 7 ultimate]
 - LiquidBounce Build Version [Latest ffe6cb6]
 - Minecraft Version [1.8.9]

**Comment by mems01** [comment] 2020-10-12 12:36
Duplicate. #229

**Comment by NurMarvin** [comment] 2020-10-12 12:56
Closing this since it's a duplicate of #229. Head over to that issue and post your system information and screenshots there instead.

**Closed by NurMarvin** 2020-10-12 12:56 UTC

**Comment by NoOrMaLN** [comment] 2020-10-13 09:57
Didn't know that was a duplicate ok.
